#!/bin/sh

#http://chee-s.net/%E3%82%B0%E3%83%AD%E3%83%BC%E3%83%90%E3%83%AB%EF%BD%89%EF%BD%90%E3%81%AE%E5%A4%89%E6%9B%B4%E3%82%92%E8%87%AA%E5%AE%85%E3%82%B5%E3%83%BC%E3%83%90%E3%81%8B%E3%82%89%E3%83%A1%E3%83%BC%E3%83%AB%E3%81%A7

newip=`wget -qO- forts.jp/ip`
oldip=`cat script/tmp/old_ip.txt`
if [ $oldip != $newip ]
	then
	echo "$newip" > script/tmp/old_ip.txt
	mutt -s "Current IP Address" "hoge@hogehoge.com" < "script/tmp/old_ip.txt"
	fi
